Update README.md
Fix for error when directory doesn't exist:

TypeError: undefined is not a function
  at workspace/features/cucumber-support/cucumber-report.js:13:12
  at FSReqWrap.oncomplete (fs.js:95:15)

if you try to nest destinationDirectory, like "reports/cucumber" this will still error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, no such file or directory '/data/jenkins/jobs/eui-qe-access-groups/workspace/report/cucumber/cucumber-test-results.json'
  at Object.fs.mkdirSync (fs.js:654:18)
  at /data/jenkins/jobs/eui-qe-access-groups/workspace/features/cucumber-support/cucumber-report.js:14:12
  at Object.oncomplete (fs.js:108:15)


the easiest fix for us was to add an mkdir -p /reports/cucumber to our jenkins job so that if a new jenkins box is spun up we can avoid the pain.